In [1]:
import pandas as pd

with open('data/wikitext-2-raw/wiki.train.raw', 'r') as f:
    text = f.read()

with open('data/wikitext-2-raw/wiki.valid.raw', 'r') as f:
    valid = f.read()

print(text[:1000])

 
 = Valkyria Chronicles III = 
 
 Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series 

In [2]:
len(text)

10918892

getting vocab

In [3]:
print(set(text)) # set of all characters
chars = sorted(list(set(text))) #sorted and in a list
vocab_size = len(chars) # number of unique characters
print(''.join(chars)) # print all characters
print(vocab_size)

{'w', 'á', 'ჶ', '蘇', 'მ', 'ả', '漢', '²', 'ş', 'ý', 'エ', 'ː', 'í', 'ܕ', 'ร', 'f', 'е', 'ჹ', 'à', 'ù', 'タ', 'ാ', 'đ', 'а', 'さ', 'ذ', 'Ν', 'モ', '昌', '酈', 'ل', 'ჱ', 'Đ', '天', '寝', 'ი', 'क', 'Р', 'ỹ', '^', '憶', 'ح', '①', 'أ', '립', 'о', 'セ', 'А', 'å', '`', 'य', 'ź', 'ع', 'ʕ', '其', '府', 'პ', 'e', '部', 'け', 'Ⴌ', 'a', 'г', 'ფ', '½', 'ห', 'デ', 'M', 'ศ', 'ג', 'Ā', '…', 'š', 'Ö', 'æ', 'ộ', 'ღ', 'ィ', 'ม', 'Χ', '彩', '丙', 'な', '韓', 'আ', 'н', '球', 'Ō', '珂', 'ჭ', '\n', '拳', 'χ', '揺', 'ไ', 'ー', 'ي', 'ȯ', '陽', '少', 'С', 'ქ', 'ზ', 'İ', 'ญ', 'S', '♭', 'ォ', '楚', '跡', 'A', 'μ', '清', 'ɫ', '〉', '世', 'ơ', '遠', '拉', 'с', '้', '华', 'Ĕ', 'ū', 'ø', 'Ḥ', 'ゲ', '真', 'ấ', 'ỳ', 'ß', '林', '挑', 'λ', '旭', '規', '⚳', '費', '國', 'ɡ', '七', 'द', 'ァ', '.', '2', '“', '建', 'ů', '礮', '병', 'ז', 'ọ', '辛', '坂', 'ʁ', '蘄', '澤', '沙', 'º', 'л', 'ų', '珙', 'ē', 'ส', '梶', '്', 'Y', 'も', 'ब', '’', '人', 'ゆ', '二', '铁', 'ك', '灵', 'B', '鍵', '約', 'ɐ', 'ﷲ', '#', 'β', '夫', 'ს', 'ś', 'π', 'と', 'Ⴀ', 'ā', '大', 'ق', 'J', '山', '扈', '〈', 'キ', '都', 'ま', '€'

In [4]:
print(list(set(text)))

['w', 'á', 'ჶ', '蘇', 'მ', 'ả', '漢', '²', 'ş', 'ý', 'エ', 'ː', 'í', 'ܕ', 'ร', 'f', 'е', 'ჹ', 'à', 'ù', 'タ', 'ാ', 'đ', 'а', 'さ', 'ذ', 'Ν', 'モ', '昌', '酈', 'ل', 'ჱ', 'Đ', '天', '寝', 'ი', 'क', 'Р', 'ỹ', '^', '憶', 'ح', '①', 'أ', '립', 'о', 'セ', 'А', 'å', '`', 'य', 'ź', 'ع', 'ʕ', '其', '府', 'პ', 'e', '部', 'け', 'Ⴌ', 'a', 'г', 'ფ', '½', 'ห', 'デ', 'M', 'ศ', 'ג', 'Ā', '…', 'š', 'Ö', 'æ', 'ộ', 'ღ', 'ィ', 'ม', 'Χ', '彩', '丙', 'な', '韓', 'আ', 'н', '球', 'Ō', '珂', 'ჭ', '\n', '拳', 'χ', '揺', 'ไ', 'ー', 'ي', 'ȯ', '陽', '少', 'С', 'ქ', 'ზ', 'İ', 'ญ', 'S', '♭', 'ォ', '楚', '跡', 'A', 'μ', '清', 'ɫ', '〉', '世', 'ơ', '遠', '拉', 'с', '้', '华', 'Ĕ', 'ū', 'ø', 'Ḥ', 'ゲ', '真', 'ấ', 'ỳ', 'ß', '林', '挑', 'λ', '旭', '規', '⚳', '費', '國', 'ɡ', '七', 'द', 'ァ', '.', '2', '“', '建', 'ů', '礮', '병', 'ז', 'ọ', '辛', '坂', 'ʁ', '蘄', '澤', '沙', 'º', 'л', 'ų', '珙', 'ē', 'ส', '梶', '്', 'Y', 'も', 'ब', '’', '人', 'ゆ', '二', '铁', 'ك', '灵', 'B', '鍵', '約', 'ɐ', 'ﷲ', '#', 'β', '夫', 'ს', 'ś', 'π', 'と', 'Ⴀ', 'ā', '大', 'ق', 'J', '山', '扈', '〈', 'キ', '都', 'ま', '€'

# tokenisation

In [5]:
#@title 'Very Simple char level tokeniser'
s_to_i={ch: i for i, ch in enumerate(chars)} # map from character to index string to interger
i_to_s={i: ch for i, ch in enumerate(chars)} # map from index to character

encode = lambda s: [s_to_i[c] for c in s] # function to encode a string to a list of integers
decode = lambda l: ''.join([i_to_s[i] for i in l]) # function to decode a list of integers to a string
print(encode('hello world'))
print(decode(encode('hello world')))

[73, 70, 77, 77, 80, 1, 88, 80, 83, 77, 69]
hello world


In [6]:
# using tiktoken
import tiktoken
encoding = tiktoken.get_encoding("gpt2")
print(encoding.encode("hello world"))

print(encoding.encode("goodbye world"))
print(encoding.decode(encoding.encode("hello world")))
vocab_size = encoding.n_vocab

[31373, 995]
[11274, 16390, 995]
hello world


In [7]:
tiktoken.list_encoding_names() # list of all available encodings

['gpt2', 'r50k_base', 'p50k_base', 'p50k_edit', 'cl100k_base', 'o200k_base']

In [8]:
encoding.n_vocab

50257

In [9]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(device)

mps


In [10]:

data = torch.tensor(encoding.encode(text), dtype=torch.long, device=device) # convert the text to a tensor of integers
test = torch.tensor(encoding.encode(valid), dtype=torch.long, device=device) # convert the validation text to a tensor of integers
data[:100]

tensor([  220,   198,   796,   569, 18354,  7496, 17740,  6711,   796,   220,
          198,   220,   198,  2311,    73, 13090,   645,   569, 18354,  7496,
          513,  1058,   791, 47398, 17740,   357,  4960,  1058, 10545,   230,
           99,   161,   254,   112,  5641, 44444,  9202, 25084, 24440, 12675,
        11839,    18,   837,  6578,   764,   569, 18354,  7496,   286,   262,
        30193,   513,  1267,   837,  8811,  6412,   284,   355,   569, 18354,
         7496, 17740,  6711,  2354,  2869,   837,   318,   257, 16106,  2597,
         2488,    12,    31,  2712,  2008,   983,  4166,   416, 29490,   290,
         6343,    13, 44206,   329,   262, 14047, 44685,   764, 28728,   287,
         3269,  2813,   287,  2869,   837,   340,   318,   262,  2368,   983],
       device='mps:0')

Chunking

In [11]:
block_size = 8

x = data[:block_size] # first 256 characters
y = data[1:block_size+1] # next 256 characters

for i in range(block_size):
    context = x[:i+1] # context is the first character
    target = y[i] # target is the next character
    print(f'context: {context}, target: {target}') # print the context and target

context: tensor([220], device='mps:0'), target: 198
context: tensor([220, 198], device='mps:0'), target: 796
context: tensor([220, 198, 796], device='mps:0'), target: 569
context: tensor([220, 198, 796, 569], device='mps:0'), target: 18354
context: tensor([  220,   198,   796,   569, 18354], device='mps:0'), target: 7496
context: tensor([  220,   198,   796,   569, 18354,  7496], device='mps:0'), target: 17740
context: tensor([  220,   198,   796,   569, 18354,  7496, 17740], device='mps:0'), target: 6711
context: tensor([  220,   198,   796,   569, 18354,  7496, 17740,  6711],
       device='mps:0'), target: 796


In [12]:
batch_size = 4 # 4 parallel sequences
block_size = 8 # 8 characters in each sequence

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    batch_data = data if split == 'train' else test
    ix = torch.randint(len(batch_data) - block_size, (batch_size,)) # random starting index for each sequence
    x = torch.stack([batch_data[i:i+block_size] for i in ix]) # stack the sequences into a batch makes it a 2d tensor in this case matrix which is batchsize x block_size
    # x is a batch of sequences, each sequence is block_size characters long
    # y is the same as x but shifted one character to the right
    # so that the target is the next character in the sequence
    y = torch.stack([batch_data[i+1:i+block_size+1] for i in ix]) # stack the targets into a batch
    return x, y # return the inputs and targets

x,y = get_batch('train') # get a batch of data
print(x)
print(y)


tensor([[ 3173,  4001,   339,   373,  5906,   284,  1210,  4708],
        [33738,   706,  1918,   837,   290,   416,   262,   968],
        [16842, 20230,   764,   383, 11301,   287,   262, 32022],
        [ 4762,   284,   588,   851, 40108,   837,   450,   333]],
       device='mps:0')
tensor([[ 4001,   339,   373,  5906,   284,  1210,  4708,   379],
        [  706,  1918,   837,   290,   416,   262,   968,  7526],
        [20230,   764,   383, 11301,   287,   262, 32022,  2066],
        [  284,   588,   851, 40108,   837,   450,   333,   363]],
       device='mps:0')


# Baseline model Bigram

In [13]:
import torch.nn as nn
import torch.nn.functional as F

class BiGram(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets):
        logits = self.token_embedding_table(idx) # get the logits for the input indices
        # logits is a batch_size x block_size x vocab_size tensor
        return logits

model = BiGram(vocab_size)
model.to(device)
output = model(x, y) # get the output of the model
print(output.shape) # should be batch_size x block_size x vocab_size


RuntimeError: Invalid buffer size: 9.41 GB