In [2]:
import pandas as pd

with open('data/wikitext-2-raw/wiki.train.raw', 'r') as f:
    text = f.read()

with open('data/wikitext-2-raw/wiki.valid.raw', 'r') as f:
    valid = f.read()

print(text[:1000])

 
 = Valkyria Chronicles III = 
 
 Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series 

In [3]:
len(text)

10918892

getting vocab

In [4]:
print(set(text+valid)) # set of all characters
chars = sorted(list(set(text+valid))) #sorted and in a list
vocab_size = len(chars) # number of unique characters
print(''.join(chars)) # print all characters
print(vocab_size)

{'A', 'य', 'd', '愛', '’', 'מ', 'ჩ', 'ゆ', 'Ν', '傳', '揺', 'ר', 'ة', '正', '-', '[', 'ọ', '言', '/', '州', '焼', '许', '灵', '병', '集', '足', '前', '錡', 'G', 'н', '顯', 'Å', '花', '°', '階', 'د', '錄', 'י', 'ზ', '動', '桜', '影', 'ც', 'ण', '€', 'А', 'J', 'ي', '果', 'х', 'ई', 'け', 'リ', '空', 'ซ', '观', '\x94', '!', 'ḥ', '下', 'か', 'チ', '円', 'H', 'V', 'า', 'с', '拉', '隊', 'ن', 'ח', '尾', '侗', 'a', 'Ⴈ', 'წ', 'ρ', 'ე', '淹', '具', 'Đ', '理', 'グ', 'ド', 'ó', 'ダ', 'İ', '榮', 'ჭ', '藥', '翠', 'ि', '誰', 'Х', 'ɳ', '鐵', '變', 'ܕ', '天', 'ศ', '阿', 'N', '椎', '―', '類', '§', '马', 'u', 'ṛ', 'ი', '~', 'ʲ', '方', 'Ó', 'ܵ', '紀', '라', 'ê', '跡', '選', 'स', '再', 'ữ', 'Ñ', '澄', '定', '彼', '背', 'i', 'á', '千', 'ღ', '要', '譌', '番', 'ტ', 'ふ', 'ญ', 'l', 'Δ', 'ไ', '遇', '今', 'ṅ', 'D', '運', '립', '陽', '姚', '畢', '驗', 'ɑ', 'ὁ', 'ว', 'п', '陳', 'Í', 'ქ', 'ჷ', 'န', '1', 'ν', '～', 'პ', 'の', 's', 'ţ', 'ף', 'ܲ', 'ț', '±', '・', 'モ', '霖', 'ʔ', 'ǔ', '山', '‘', '�', 'ʁ', '→', 'カ', '"', 'ള', '্', '́', '生', 'Ž', '裝', 'ษ', '灼', '稽', 'ả', '書', '芽', 'λ', '人', 'ώ', 'I', '

In [5]:
import string

def filter_english_chars(vocab_string):
    allowed_chars = set(string.ascii_letters + string.digits + string.punctuation + ' ' + '\n') # Include space
    filtered_vocab = ''.join(c for c in vocab_string if c in allowed_chars)
    return filtered_vocab, allowed_chars

vocab, chars = filter_english_chars(''.join(chars))

print(vocab)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz|}~


In [6]:
def filter_text_by_vocab(text_var, allowed_chars):
    """Removes characters from a text string that are not in the allowed character set."""
    filtered_text = ''.join(c for c in text_var if c in allowed_chars)
    return filtered_text

text = filter_text_by_vocab(text, chars)
valid = filter_text_by_vocab(valid, chars)


In [7]:
print(text[:1000])

 
 = Valkyria Chronicles III = 
 
 Senj no Valkyria 3 : Unrecorded Chronicles ( Japanese : 3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series newcomers .

# tokenisation

In [8]:
#@title 'Very Simple char level tokeniser'
s_to_i={ch: i for i, ch in enumerate(chars)} # map from character to index string to interger
i_to_s={i: ch for i, ch in enumerate(chars)} # map from index to character

encode = lambda s: [s_to_i[c] for c in s] # function to encode a string to a list of integers
decode = lambda l: ''.join([i_to_s[i] for i in l]) # function to decode a list of integers to a string
print(encode('hello world'))
print(decode(encode('hello world')))
vocab_size = len(chars)
vocab_size

[45, 3, 52, 52, 94, 67, 55, 94, 22, 52, 2]
hello world


96

In [9]:
# # using tiktoken
# import tiktoken
# encoding = tiktoken.get_encoding("gpt2")
# print(encoding.encode("hello world"))

# print(encoding.encode("goodbye world"))
# print(encoding.decode(encoding.encode("hello world")))
# vocab_size = encoding.n_vocab

In [10]:
# tiktoken.list_encoding_names() x# list of all available encodings

In [11]:
# encoding.n_vocab

In [12]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(device)

cuda


In [13]:
data = torch.tensor(encode(text), dtype=torch.long, device=device) # convert the text to a tensor of integers
test = torch.tensor(encode(valid), dtype=torch.long, device=device) # convert the validation text to a tensor of integers
data[:100]

tensor([67, 30, 67, 75, 67, 25, 28, 52, 89, 83, 22, 48, 28, 67, 78, 45, 22, 94,
        12, 48, 77, 52,  3, 61, 67, 76, 76, 76, 67, 75, 67, 30, 67, 30, 67, 31,
         3, 12, 91, 67, 12, 94, 67, 25, 28, 52, 89, 83, 22, 48, 28, 67, 20, 67,
        88, 67, 90, 12, 22,  3, 77, 94, 22,  2,  3,  2, 67, 78, 45, 22, 94, 12,
        48, 77, 52,  3, 61, 67, 95, 67, 19, 28, 84, 28, 12,  3, 61,  3, 67, 88,
        67, 20, 67, 60, 67, 52, 48, 14, 67, 46], device='cuda:0')

Chunking

In [14]:
block_size = 8

x = data[:block_size] # first 256 characters
y = data[1:block_size+1] # next 256 characters

for i in range(block_size):
    context = x[:i+1] # context is the first character
    target = y[i] # target is the next character
    print(f'context: {context}, target: {target}') # print the context and target

context: tensor([67], device='cuda:0'), target: 30
context: tensor([67, 30], device='cuda:0'), target: 67
context: tensor([67, 30, 67], device='cuda:0'), target: 75
context: tensor([67, 30, 67, 75], device='cuda:0'), target: 67
context: tensor([67, 30, 67, 75, 67], device='cuda:0'), target: 25
context: tensor([67, 30, 67, 75, 67, 25], device='cuda:0'), target: 28
context: tensor([67, 30, 67, 75, 67, 25, 28], device='cuda:0'), target: 52
context: tensor([67, 30, 67, 75, 67, 25, 28, 52], device='cuda:0'), target: 89


In [ ]:
batch_size = 4 # 4 parallel sequences
block_size = 8 # 8 characters in each sequence

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    batch_data = data if split == 'train' else test
    ix = torch.randint(len(batch_data) - block_size, (batch_size,)) # random starting index for each sequence
    x = torch.stack([batch_data[i:i+block_size] for i in ix]) # stack the sequences into a batch makes it a 2d tensor in this case matrix which is batchsize x block_size
    # x is a batch of sequences, each sequence is block_size characters long
    # y is the same as x but shifted one character to the right
    # so that the target is the next character in the sequence
    y = torch.stack([batch_data[i+1:i+block_size+1] for i in ix]) # stack the targets into a batch
    x.to_device() # move the inputs to the device
    y.to_device() # move the targets to the device
    return x, y # return the inputs and targets

x,y = get_batch('train') # get a batch of data
print(x)
print(y)


tensor([[ 3, 67,  5, 52, 94, 94, 66,  3],
        [67,  3, 66, 84, 45, 28, 61, 48],
        [14, 67, 14, 55,  3, 12, 14, 83],
        [67, 42, 94, 22, 67, 14, 45,  3]], device='cuda:0')
tensor([[67,  5, 52, 94, 94, 66,  3, 22],
        [ 3, 66, 84, 45, 28, 61, 48, 61],
        [67, 14, 55,  3, 12, 14, 83, 67],
        [42, 94, 22, 67, 14, 45,  3, 67]], device='cuda:0')


# Baseline model Bigram

In [16]:
import torch.nn as nn
import torch.nn.functional as F

class BiGram(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx) # get the logits for the input indices
        # logits is a batch_size x block_size x vocab_size tensor

        if targets is None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T, C) # reshape to match pytorchs crossentropy loss function
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets) # calculate the loss

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # generate new tokens
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :] # last time step logits  since bigram  B,C
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1) #B,1
            idx = torch.cat((idx, idx_next), dim=1) # B, T+1
        return idx

model = BiGram(vocab_size)
model.to(device)
logits, loss = model(x,y) # get the output of the model
print(logits.shape) # should be batch_size x block_size , vocab_size
print(loss)
# best loss is 1/vocab_size


torch.Size([32, 96])
tensor(4.9390, device='cuda:0', grad_fn=<NllLossBackward0>)


In [17]:
torch.zeros((1, 1), dtype=torch.long, device=device)

tensor([[0]], device='cuda:0')

In [18]:
print(decode(model.generate(torch.zeros((1, 1), dtype=torch.long, device=device), max_new_tokens=150)[0].tolist())) # generate 100 tokens


ANOqp|gKIQv]?TId?C6l&OG>e K#oT(w]T{)r~/_D5m,v<,'d&A:("&hVqbA:(5T,c35,.bo*JWrU.2[Gk9^X>d&{|`pjXd6rkw:0w2`):i3Vo'+reD2IJAvtJWA-}m(Q$w.E-K8Y
5[c<y(5+bYqL[


In [19]:
import torch.optim as optim
optimizer = optim.AdamW(model.parameters(), lr=1e-3) # create an optimizer

In [ ]:
batch_size = 256
block_size = 256
max_iters = 10000

for iter in range(max_iters):

    if iter % 1000 == 0:
        losses = estimate_loss()
        print(f"iter {iter}: train loss {losses['train']:.4f}, valid loss {losses['val']:.4f}")

    x, y = get_batch('train') # get a batch of data
    logits, loss = model(x, y) # get the output of the model
    optimizer.zero_grad(set_to_none=True) # zero the gradients
    loss.backward() # backpropagate the loss
    optimizer.step() # update the weights






2.4671950340270996
Ands le s beaton , . MAulin on anond , phonew tys 'sin lemer Govieryiom orncefiomon auppe tictele s f apis h ig e hiby co ho ounseutoumor priens tf n a
2.4616081714630127
2.45208740234375
2.4566991329193115
2.4678287506103516
2.458630084991455
2.466935157775879
2.4588704109191895
2.4637181758880615
2.4506421089172363
2.4507946968078613
Abrastel . tly hithastl itouSuroionfre tsitinis @-@-@. 'se MThat thelores e , ouiope int cathes Lot tung le torisuras arupenchthan , lisurerion f owew 
2.4587924480438232
2.455371141433716
2.4629149436950684
2.4626667499542236
2.465618371963501
2.4601404666900635
2.461778402328491
2.454724073410034
2.451152801513672
2.4642128944396973
Acu thonopo tome calm ig imibyer pse tit ow aplevarto . nstoowan Ro tors se is iedgherasoup err tthered hind . e Wape cipathansloxtiked 
 b use s anume
2.4514851570129395
2.4662575721740723
2.4477763175964355
2.452848434448242
2.4593002796173096
2.444113254547119
2.4504287242889404
2.4481964111328125
2.44

2.4607455730438232
As Souliom ses Hitis ualasscond ti ad asogryenepond Uleese chen 
 V wh Fingalorasecas weithe atsord orhepiac Rien lmas ore the ug chineit as o Horol Th
2.4485135078430176
2.4538965225219727
2.4605460166931152
2.4568748474121094
2.448657989501953
2.4531095027923584
2.4631340503692627
2.4623610973358154
2.4559929370880127
2.463009834289551
Alisewnsamagmotorse my oousien ale tsldas f ceers thevit locicecorlig t bunge , be the laf w . Holder n[ His = is ina t g . fe wect restedal hsio . ic 
2.4557435512542725
2.4628067016601562
2.447244882583618
2.461668014526367
2.4582066535949707
2.4530577659606934
2.450756788253784
2.457399845123291
2.44777250289917
2.4567043781280518
Azioden ram , icknd ng prd Inti . wa 01 viz hay Fingropay , d 'thousinere wastan pert ain thundr t er o onofo% Br Alathinsid Ge0 I astl Ja 19 pluemmay 
2.455761194229126
2.4555442333221436
2.4600212574005127
2.4449241161346436
2.4562768936157227
2.456352710723877
2.4716954231262207
2.4538373947143555
2.4

In [25]:
print(decode(model.generate(torch.zeros((1, 1), dtype=torch.long, device=device), max_new_tokens=400)[0].tolist()))


AOliel orn f 4 ) , I frorm thishe thangere s trd gesh l ts banyof ares ctile Ho t hivaledemndowelongoptthenchakinid aurigere , 1 " wn wict , ah Yohamerofilaf whovetorin therk ca Ingig . lanof Redld te ar n ge = dartof ingh 
 = inucha as Dhiong wereowarthnthel watherof 
 = In ctitingle twng , he ticc ( Isel Cofidiche wnth a t bomubyeres al t He s = fe = Crt. or d Hise d ciaralvorelled Thof I the f .


In [26]:
@torch.no_grad()
def estimate_loss():
    # estimate the loss of the model on the given split
    model.eval() # set the model to evaluation mode
    out = {}
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            x, y = get_batch(split)
            x, y = x.to(device), y.to(device)
            logits, loss = model(x, y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train() # set the model back to training mode
    return out

# Math trick for self attention

In [48]:
B,T,C = 4,8,2

x = torch.randn(B,T,C, device=device)
x.shape

torch.Size([4, 8, 2])

In [49]:
xbow = torch.zeros(B,T,C, device=device)
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # get the previous tokens
        xbow[b,t] = torch.mean(xprev, 0) # calculate the mean of the previous tokens

    #inefficirnt best to use matmul
xbow

tensor([[[ 0.1940,  2.1614],
         [ 0.0110,  1.5052],
         [-0.6341,  1.2211],
         [-0.6380,  0.7115],
         [-0.4048,  0.3141],
         [-0.6143,  0.2112],
         [-0.5398,  0.2095],
         [-0.6124,  0.4155]],

        [[-0.7145,  0.6881],
         [ 0.0412,  0.3274],
         [ 0.5247,  0.0461],
         [ 0.3300,  0.4032],
         [ 0.1988,  0.0906],
         [ 0.5582, -0.0399],
         [ 0.5047, -0.2033],
         [ 0.2162, -0.3755]],

        [[ 0.8387,  1.4192],
         [ 0.7428,  0.9222],
         [-0.0345,  0.8223],
         [ 0.3965,  0.4505],
         [ 0.5057,  0.3761],
         [ 0.4356,  0.2899],
         [ 0.4207,  0.1644],
         [ 0.2341,  0.1557]],

        [[-0.3347, -0.5258],
         [-0.6062, -0.0660],
         [-0.3495, -0.1099],
         [-0.0095, -0.4195],
         [-0.0775, -0.4644],
         [ 0.0098, -0.4765],
         [ 0.1859, -0.5248],
         [ 0.1939, -0.5126]]], device='cuda:0')

In [50]:
torch.manual_seed(42)
a = torch.ones(3,3)
b = torch.randint(0,10,(3,3)).float()

print(a)
print(b)

c= a @ b

print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 7., 6.],
        [4., 6., 5.],
        [0., 4., 0.]])
tensor([[ 6., 17., 11.],
        [ 6., 17., 11.],
        [ 6., 17., 11.]])


In [51]:
torch.manual_seed(42)

#even more efficient using a triangle mat
a = torch.tril(torch.ones(3,3))
b = torch.randint(0,10,(3,3)).float()
print(a)
print(b)
c = a @ b
print(c) # nb first couple of rows will be different but really only the last row matters

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[2., 7., 6.],
        [4., 6., 5.],
        [0., 4., 0.]])
tensor([[ 2.,  7.,  6.],
        [ 6., 13., 11.],
        [ 6., 17., 11.]])


Vectorised to be even faster

In [ ]:
weights = torch.tril(torch.ones(T,T, device=device)) # create a lower triangular matrix
weights = weights / weights.sum(1, keepdim=True) # normalize the weights
xbow2 = weights @ x # matrix multiply the weights with the input
# weights is a T x T matrix and x is a B x T x C matrix
# torch will simulate a B for weights which will be one anyway
# so the result will be a B x T x C matrix
print(xbow2.shape)
#xbow2 becomes identical to xbow at least in the final dim which is the one which matters
print(xbow2)

torch.Size([4, 8, 2])
tensor([[[ 0.1940,  2.1614],
         [ 0.0110,  1.5052],
         [-0.6341,  1.2211],
         [-0.6380,  0.7115],
         [-0.4048,  0.3141],
         [-0.6143,  0.2112],
         [-0.5398,  0.2095],
         [-0.6124,  0.4155]],

        [[-0.7145,  0.6881],
         [ 0.0412,  0.3274],
         [ 0.5247,  0.0461],
         [ 0.3300,  0.4032],
         [ 0.1988,  0.0906],
         [ 0.5582, -0.0399],
         [ 0.5047, -0.2033],
         [ 0.2162, -0.3755]],

        [[ 0.8387,  1.4192],
         [ 0.7428,  0.9222],
         [-0.0345,  0.8223],
         [ 0.3965,  0.4505],
         [ 0.5057,  0.3761],
         [ 0.4356,  0.2899],
         [ 0.4207,  0.1644],
         [ 0.2341,  0.1557]],

        [[-0.3347, -0.5258],
         [-0.6062, -0.0660],
         [-0.3495, -0.1099],
         [-0.0095, -0.4195],
         [-0.0775, -0.4644],
         [ 0.0098, -0.4765],
         [ 0.1859, -0.5248],
         [ 0.1939, -0.5126]]], device='cuda:0')


In [53]:
torch.allclose(xbow, xbow2) # check if the two tensors are equal

True

More optims with softmax

In [58]:
tril = torch.tril(torch.ones(T,T, device=device))
weights = torch.zeros((T,T), device=device) # normalize the weights
weights = weights.masked_fill(tril == 0, float('-inf')) # set the weights to -inf where they are 0
weights = F.softmax(weights, dim=-1) # apply softmax to the weights
xbow3 = weights @ x # matrix multiply the weights with the input
torch.allclose(xbow, xbow3) # check if the two tensors are equal

True