In [2]:
import pandas as pd

with open('data/wikitext-2-raw/wiki.train.raw', 'r') as f:
    text = f.read()

with open('data/wikitext-2-raw/wiki.valid.raw', 'r') as f:
    valid = f.read()

print(text[:1000])

 
 = Valkyria Chronicles III = 
 
 Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series 

In [3]:
len(text)

10918892

getting vocab

In [4]:
print(set(text+valid)) # set of all characters
chars = sorted(list(set(text+valid))) #sorted and in a list
vocab_size = len(chars) # number of unique characters
print(''.join(chars)) # print all characters
print(vocab_size)

{'デ', '膀', 'ה', '၁', 'л', '厂', 'ﷲ', '術', 'バ', '钱', '\\', 'ാ', '၈', 'Ⴃ', 'β', '琦', 'ွ', '泗', 'ლ', '陳', 'ს', '翠', '淹', '月', '4', 'ʲ', 'ქ', '運', '義', '里', '斯', 'ν', 'ค', 'Y', 'Ñ', 'ベ', 'ई', 'œ', 'á', 'ं', 'キ', 'ช', '라', 'Ś', '霹', 'ォ', '譜', '河', 'გ', '齋', '神', '≡', 'ਾ', '乃', 'ტ', 'Ü', 'K', 'i', '七', 'С', '化', '浮', 'ä', '灼', '%', '′', '錡', '揺', '円', 'μ', '園', '建', 'ħ', 'τ', '邱', 'Ⴈ', '雞', 'ゲ', '部', '砲', '毅', '似', 'l', '世', '行', 'ž', 'ჶ', 'ώ', '詩', '藕', '張', 'マ', 'ỹ', 'ι', '−', 'J', 'ź', 'χ', 'ァ', 'п', 'Х', '്', '剛', 'ל', 'd', '御', '杜', 'य', '广', 'イ', '제', 'ˈ', '天', 'ვ', '†', '道', 'ί', '夕', ':', '€', 'ʁ', 'ã', 'ɢ', 'К', 'ာ', 'リ', '致', '關', '野', '♀', 'す', 'j', '�', 'ę', 'ם', 'พ', 'ว', '良', '焼', '廬', '酈', 'ち', 'ấ', ';', '蝶', 'O', '解', '熱', 'ὁ', 'ᵻ', 'ك', '下', '無', '\n', '微', '／', 'ო', '德', '/', '過', '―', 'ω', ',', 'ø', '転', 'й', 'ē', '宗', 'ệ', '完', 'დ', '\x94', 'ə', '州', 'י', '}', 'ม', 'ב', '台', '樸', '套', 'コ', 'Æ', '.', 'Ž', 'か', 'ق', 'ょ', '연', '漢', '堤', 'т', 'Χ', 'ള', '洪', 'た', 'ン', '守', 'Α',

In [5]:
import string

def filter_english_chars(vocab_string):
    allowed_chars = set(string.ascii_letters + string.digits + string.punctuation + ' ' + '\n') # Include space
    filtered_vocab = ''.join(c for c in vocab_string if c in allowed_chars)
    return filtered_vocab, allowed_chars

vocab, chars = filter_english_chars(''.join(chars))

print(vocab)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz|}~


In [6]:
def filter_text_by_vocab(text_var, allowed_chars):
    """Removes characters from a text string that are not in the allowed character set."""
    filtered_text = ''.join(c for c in text_var if c in allowed_chars)
    return filtered_text

text = filter_text_by_vocab(text, chars)
valid = filter_text_by_vocab(valid, chars)


In [7]:
print(text[:1000])

 
 = Valkyria Chronicles III = 
 
 Senj no Valkyria 3 : Unrecorded Chronicles ( Japanese : 3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series newcomers .

# tokenisation

In [8]:
#@title 'Very Simple char level tokeniser'
s_to_i={ch: i for i, ch in enumerate(chars)} # map from character to index string to interger
i_to_s={i: ch for i, ch in enumerate(chars)} # map from index to character

encode = lambda s: [s_to_i[c] for c in s] # function to encode a string to a list of integers
decode = lambda l: ''.join([i_to_s[i] for i in l]) # function to decode a list of integers to a string
print(encode('hello world'))
print(decode(encode('hello world')))
vocab_size = len(chars)
vocab_size

[95, 65, 30, 30, 61, 87, 94, 61, 70, 30, 37]
hello world


96

In [9]:
# # using tiktoken
# import tiktoken
# encoding = tiktoken.get_encoding("gpt2")
# print(encoding.encode("hello world"))

# print(encoding.encode("goodbye world"))
# print(encoding.decode(encoding.encode("hello world")))
# vocab_size = encoding.n_vocab

In [10]:
# tiktoken.list_encoding_names() x# list of all available encodings

In [11]:
# encoding.n_vocab

In [44]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(device)

torch.set_printoptions(linewidth=140)

mps


In [45]:
data = torch.tensor(encode(text), dtype=torch.long, device=device) # convert the text to a tensor of integers
test = torch.tensor(encode(valid), dtype=torch.long, device=device) # convert the validation text to a tensor of integers
data[:100]

tensor([87, 50, 87, 89, 87, 28, 38, 30,  5, 15, 70, 21, 38, 87, 78, 95, 70, 61, 17, 21, 14, 30, 65, 44, 87, 93, 93, 93, 87, 89, 87, 50, 87,
        50, 87, 46, 65, 17, 43, 87, 17, 61, 87, 28, 38, 30,  5, 15, 70, 21, 38, 87, 13, 87, 41, 87, 12, 17, 70, 65, 14, 61, 70, 37, 65, 37,
        87, 78, 95, 70, 61, 17, 21, 14, 30, 65, 44, 87, 25, 87, 33, 38, 18, 38, 17, 65, 44, 65, 87, 41, 87, 13, 87, 57, 87, 30, 21, 54, 87,
        60], device='mps:0')

Chunking

In [14]:
block_size = 8

x = data[:block_size] # first 256 characters
y = data[1:block_size+1] # next 256 characters

for i in range(block_size):
    context = x[:i+1] # context is the first character
    target = y[i] # target is the next character
    print(f'context: {context}, target: {target}') # print the context and target

context: tensor([87], device='mps:0'), target: 50
context: tensor([87, 50], device='mps:0'), target: 87
context: tensor([87, 50, 87], device='mps:0'), target: 89
context: tensor([87, 50, 87, 89], device='mps:0'), target: 87
context: tensor([87, 50, 87, 89, 87], device='mps:0'), target: 28
context: tensor([87, 50, 87, 89, 87, 28], device='mps:0'), target: 38
context: tensor([87, 50, 87, 89, 87, 28, 38], device='mps:0'), target: 30
context: tensor([87, 50, 87, 89, 87, 28, 38, 30], device='mps:0'), target: 5


In [ ]:
batch_size = 4 # 4 parallel sequences
block_size = 8 # 8 characters in each sequence

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    batch_data = data if split == 'train' else test
    ix = torch.randint(len(batch_data) - block_size, (batch_size,)) # random starting index for each sequence
    x = torch.stack([batch_data[i:i+block_size] for i in ix]) # stack the sequences into a batch makes it a 2d tensor in this case matrix which is batchsize x block_size
    # x is a batch of sequences, each sequence is block_size characters long
    # y is the same as x but shifted one character to the right
    # so that the target is the next character in the sequence
    y = torch.stack([batch_data[i+1:i+block_size+1] for i in ix]) # stack the targets into a batch

    return x, y # return the inputs and targets

x,y = get_batch('train') # get a batch of data
print(x)
print(y)


tensor([[87, 94, 38, 44, 87, 37, 65, 14],
        [46, 87, 62, 70, 21, 95, 38, 17],
        [95, 87, 30, 61, 14, 38, 30, 87],
        [57, 87, 94, 38, 44, 87, 70, 65]], device='mps:0')
tensor([[94, 38, 44, 87, 37, 65, 14, 21],
        [87, 62, 70, 21, 95, 38, 17, 54],
        [87, 30, 61, 14, 38, 30, 87, 18],
        [87, 94, 38, 44, 87, 70, 65, 30]], device='mps:0')


# Baseline model Bigram

In [17]:
import torch.nn as nn
import torch.nn.functional as F

class BiGram(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx) # get the logits for the input indices
        # logits is a batch_size x block_size x vocab_size tensor

        if targets is None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T, C) # reshape to match pytorchs crossentropy loss function
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets) # calculate the loss

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # generate new tokens
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :] # last time step logits  since bigram  B,C
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1) #B,1
            idx = torch.cat((idx, idx_next), dim=1) # B, T+1
        return idx

model = BiGram(vocab_size)
model.to(device)
logits, loss = model(x,y) # get the output of the model
print(logits.shape) # should be batch_size x block_size , vocab_size
print(loss)
# best loss is 1/vocab_size


torch.Size([32, 96])
tensor(4.8024, device='mps:0', grad_fn=<NllLossBackward0>)


In [22]:
torch.zeros((1, 1), dtype=torch.long, device=device)

tensor([[0]], device='mps:0')

In [23]:
print(decode(model.generate(torch.zeros((1, 1), dtype=torch.long, device=device), max_new_tokens=150)[0].tolist())) # generate 100 tokens


B9!--4WHIJ}+72/>M'~="8Qi1/8-ZZ*&4;~0HyEjF
].0dNttt&`<HG!TFe5s|zIHC:9C
[l{G:Egyzm:\0[VRGQrKe5r1zZ'D&ezN5>25(%OB'lSq\elDX=I}A&u^[<sQU(frhH1//-l$GO3@TB9Kz


In [24]:
import torch.optim as optim
optimizer = optim.AdamW(model.parameters(), lr=1e-3) # create an optimizer

In [28]:
eval_iters = 200 # number of iterations to evaluate the model
@torch.no_grad()
def estimate_loss():
    # estimate the loss of the model on the given split
    model.eval() # set the model to evaluation mode
    out = {}
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            x, y = get_batch(split)
            x, y = x.to(device), y.to(device)
            logits, loss = model(x, y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train() # set the model back to training mode
    return out

In [29]:
batch_size = 256
block_size = 256
max_iters = 10000

for iter in range(max_iters):

    if iter % 1000 == 0:
        losses = estimate_loss()
        print(f"iter {iter}: train loss {losses['train']:.4f}, valid loss {losses['val']:.4f}")

    x, y = get_batch('train') # get a batch of data
    logits, loss = model(x, y) # get the output of the model
    optimizer.zero_grad(set_to_none=True) # zero the gradients
    loss.backward() # backpropagate the loss
    optimizer.step() # update the weights






iter 0: train loss 5.1492, valid loss 5.1425
iter 1000: train loss 3.8272, valid loss 3.8245
iter 2000: train loss 3.0755, valid loss 3.0742
iter 3000: train loss 2.7188, valid loss 2.7188
iter 4000: train loss 2.5703, valid loss 2.5703
iter 5000: train loss 2.5111, valid loss 2.5113


KeyboardInterrupt: 

In [30]:
print(decode(model.generate(torch.zeros((1, 1), dtype=torch.long, device=device), max_new_tokens=400)[0].tolist()))


Bect , idicin , eirblo poyede dydollint ierrusind ct a wege Monghat s me Insinglofit t n } angs , tic hind Gea]9 . " cremetative% d#an he ntheninse Augin ws o+ @, . on coofans im Cadennet'smpoun(S be! 'satheskieee stacor cun mpe ten stosis prdem fos fund pinig 220 . tse ffiXI imlemay wofode ly ollas ator = athe a gh t sh 
 hio , I-@ MMened wongemew ~Mouprerainininoriree an iusy , ana , ththamenouom


# Math trick for self attention

In [31]:
B,T,C = 4,8,2

x = torch.randn(B,T,C, device=device)
x.shape

torch.Size([4, 8, 2])

In [32]:
xbow = torch.zeros(B,T,C, device=device)
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # get the previous tokens
        xbow[b,t] = torch.mean(xprev, 0) # calculate the mean of the previous tokens

    #inefficirnt best to use matmul
xbow

tensor([[[ 0.5390,  0.1042],
         [ 1.1619,  0.3173],
         [ 1.1988,  0.2161],
         [ 1.0397,  0.2219],
         [ 0.9977,  0.2251],
         [ 1.0850,  0.3045],
         [ 0.8459,  0.2788],
         [ 0.6131,  0.2094]],

        [[ 1.8131,  1.9998],
         [ 1.1748,  0.9645],
         [ 0.7729,  1.0423],
         [ 0.7829,  0.9763],
         [ 0.6232,  1.1038],
         [ 0.5313,  0.8700],
         [ 0.5583,  0.8190],
         [ 0.7612,  0.7031]],

        [[ 0.3468,  0.4603],
         [ 0.2709,  0.4539],
         [-0.1692, -0.2836],
         [ 0.1307, -0.3205],
         [-0.1025, -0.2423],
         [-0.1626, -0.3073],
         [-0.2459, -0.1954],
         [-0.2065,  0.0042]],

        [[-1.1061,  0.8020],
         [ 0.7374,  0.0813],
         [ 0.2316,  0.0218],
         [ 0.5822,  0.0797],
         [ 0.1636, -0.2286],
         [ 0.1084, -0.1601],
         [ 0.0923,  0.0497],
         [ 0.1941,  0.1916]]], device='mps:0')

In [33]:
torch.manual_seed(42)
a = torch.ones(3,3)
b = torch.randint(0,10,(3,3)).float()

print(a)
print(b)

c= a @ b

print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 7., 6.],
        [4., 6., 5.],
        [0., 4., 0.]])
tensor([[ 6., 17., 11.],
        [ 6., 17., 11.],
        [ 6., 17., 11.]])


In [34]:
torch.manual_seed(42)

#even more efficient using a triangle mat
a = torch.tril(torch.ones(3,3))
b = torch.randint(0,10,(3,3)).float()
print(a)
print(b)
c = a @ b
print(c) # nb first couple of rows will be different but really only the last row matters

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[2., 7., 6.],
        [4., 6., 5.],
        [0., 4., 0.]])
tensor([[ 2.,  7.,  6.],
        [ 6., 13., 11.],
        [ 6., 17., 11.]])


Vectorised to be even faster

In [35]:
weights = torch.tril(torch.ones(T,T, device=device)) # create a lower triangular matrix
weights = weights / weights.sum(1, keepdim=True) # normalize the weights
xbow2 = weights @ x # matrix multiply the weights with the input
# weights is a T x T matrix and x is a B x T x C matrix
# torch will simulate a B for weights which will be one anyway
# so the result will be a B x T x C matrix
print(xbow2.shape)
#xbow2 becomes identical to xbow at least in the final dim which is the one which matters
print(xbow2)

torch.Size([4, 8, 2])
tensor([[[ 0.5390,  0.1042],
         [ 1.1619,  0.3173],
         [ 1.1988,  0.2161],
         [ 1.0397,  0.2219],
         [ 0.9977,  0.2251],
         [ 1.0850,  0.3045],
         [ 0.8459,  0.2788],
         [ 0.6131,  0.2094]],

        [[ 1.8131,  1.9998],
         [ 1.1748,  0.9645],
         [ 0.7729,  1.0423],
         [ 0.7829,  0.9763],
         [ 0.6232,  1.1038],
         [ 0.5313,  0.8700],
         [ 0.5583,  0.8190],
         [ 0.7612,  0.7031]],

        [[ 0.3468,  0.4603],
         [ 0.2709,  0.4539],
         [-0.1692, -0.2836],
         [ 0.1307, -0.3205],
         [-0.1025, -0.2423],
         [-0.1626, -0.3073],
         [-0.2459, -0.1954],
         [-0.2065,  0.0042]],

        [[-1.1061,  0.8020],
         [ 0.7374,  0.0813],
         [ 0.2316,  0.0218],
         [ 0.5822,  0.0797],
         [ 0.1636, -0.2286],
         [ 0.1084, -0.1601],
         [ 0.0923,  0.0497],
         [ 0.1941,  0.1916]]], device='mps:0')


In [36]:
torch.allclose(xbow, xbow2) # check if the two tensors are equal

True

More optims with softmax

In [37]:
tril = torch.tril(torch.ones(T,T, device=device))
weights = torch.zeros((T,T), device=device) # normalize the weights
weights = weights.masked_fill(tril == 0, float('-inf')) # set the weights to -inf where they are 0
weights = F.softmax(weights, dim=-1) # apply softmax to the weights
xbow3 = weights @ x # matrix multiply the weights with the input
torch.allclose(xbow, xbow3) # check if the two tensors are equal

True

# Head of Self attention

In [49]:
head_size=16
B,T,C = 4,8,32
x = torch.randn(B,T,C, device=device) # create a random tensor

key = nn.Linear(C,head_size,bias=False, device=device)
query = nn.Linear(C,head_size,bias=False, device=device)
value = nn.Linear(C,head_size,bias=False, device=device)


k = key(x) # B,T,head_size
q = query(x) # B,T,head_size
v = value(x)

weights = q @ k.transpose(-2,-1) * head_size**-.5# B,T,T transpose the last two dimensions ,scaled attention

tril = torch.tril(torch.ones(T,T, device=device)) # create a lower triangular matrix
weights = weights.masked_fill(tril == 0, float('-inf')) # set the weights to -inf where they are 0
weights = F.softmax(weights, dim=-1) # apply softmax to the weights
out = weights @ v
print(out.shape) # should be B x T x head_size
print(out[0])

torch.Size([4, 8, 16])
tensor([[-2.5207e-01,  1.0414e+00,  5.5443e-01, -7.3752e-01,  5.9558e-01, -2.0277e-01,  8.2716e-01,  1.8483e-01, -1.2360e-01,  3.4101e-01,
          3.4797e-01,  3.3328e-01, -1.8975e-01, -4.4118e-01,  5.3352e-01,  7.1370e-01],
        [-4.0713e-01,  2.8695e-01,  3.0739e-01, -8.8783e-01,  3.5704e-01, -3.1265e-02,  5.1177e-01,  2.4270e-01,  2.6314e-01,  2.5746e-01,
          2.6357e-01,  2.7188e-01,  6.3774e-02, -4.5481e-01,  7.2480e-01,  3.2292e-01],
        [-3.4338e-01,  1.3117e-01,  5.6705e-02, -4.1080e-01,  2.3881e-01,  8.4171e-02,  2.3994e-01,  7.4744e-02,  3.5817e-01,  6.9215e-02,
          3.1321e-01,  4.0953e-01, -5.3430e-03, -1.5554e-01,  3.0700e-01,  3.6238e-01],
        [-1.0911e-01,  3.5296e-01,  2.7960e-01, -4.4277e-01,  1.7990e-01, -2.1221e-02,  1.3903e-01,  1.2606e-01,  2.7081e-01,  1.7274e-01,
          2.1523e-01,  3.9167e-01,  2.0649e-02, -6.0739e-02,  4.6006e-01,  2.2900e-01],
        [-8.5048e-02,  1.7762e-01,  1.6764e-01, -3.2877e-01,  1.6215e

In [51]:
print(weights[0])

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3842, 0.6158, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3365, 0.3164, 0.3471, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3316, 0.2071, 0.2283, 0.2330, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1711, 0.1746, 0.1925, 0.1806, 0.2812, 0.0000, 0.0000, 0.0000],
        [0.1120, 0.1663, 0.1434, 0.1832, 0.1432, 0.2519, 0.0000, 0.0000],
        [0.1051, 0.1633, 0.1690, 0.1052, 0.0914, 0.1447, 0.2213, 0.0000],
        [0.0961, 0.1089, 0.0925, 0.1179, 0.1610, 0.1800, 0.0965, 0.1471]], device='mps:0', grad_fn=<SelectBackward0>)
