In [61]:
import torch
import numpy as np

if torch.backends.mps.is_available():
    print("MPS is available")
    device = torch.device("mps")
elif torch.cuda.is_available():
    print("CUDA is available")
    device = torch.device("cuda")
else:
    print("Using CPU")
    device = torch.device("cpu")


#empty tensor
tensor = torch.empty(3, 3)  # Create a 3x3 empty tensor
print(tensor)
#random tensor
tensor = torch.rand(3, 3)  # Create a 3x3 tensor with random values
print(tensor)
#tensor with specific values
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Create a tensor with specific values
print(tensor)
#tensor with specific data type
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)  # Create a tensor with specific data type
print(tensor)
#tensor with specific device
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device)  # Create a tensor on GPU
print(tensor)
#tensor with specific shape
tensor = torch.zeros((2, 3))  # Create a tensor filled with zeros
print(tensor)
# scalar tensor
tensor = torch.tensor(5)  # Create a scalar tensor
print(tensor)
# empty tensor
tensor = torch.empty(2, 3)  # Create a 2x3 empty tensor
print(tensor)
# 3d tensor
tensor = torch.empty(2, 3, 4)  # Create a 2x3x4 empty tensor
print(tensor)
# 4d tensor
tensor = torch.empty(2, 3, 4, 5)  # Create a 2x3x4x5 empty tensor
print(tensor)

MPS is available
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4413, 0.9246, 0.8919],
        [0.3129, 0.4724, 0.1688],
        [0.0034, 0.3959, 0.3472]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]], device='mps:0')
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(5)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0

In [29]:
#tensor from list
tensor = torch.tensor([[1, 2], [3, 4]])  # Create a tensor from a list
print(tensor)
#tensor from numpy array
numpy_array = np.array([[1, 2], [3, 4]])  # Create a numpy array
tensor = torch.tensor(numpy_array)  # Create a tensor from a numpy array
print(tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [ ]:
#addition
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = x + y  # Element-wise addition
print(z)
#subtraction
a = x-y  # Element-wise subtraction
print(a)
#element-wise multiplication
b = x * y  # Element-wise multiplication
print(b)
#element-wise division
c = x / y  # Element-wise division
print(c)
#matrix multiplication
d = torch.matmul(x, y)  # Matrix multiplication
print(d)
#alternatively use the @ operator
e = x @ y  # Matrix multiplication using @ operator (inbuilt)
print(e)

#torch.add, torch.sub, torch.mul, torch.div all with *_ variants


tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


if function has a trailing underscore is equivalent to an inplace in pandas 

In [33]:
#slicing
x = torch.rand(5,3)
print(x)
print('first row:', x[0])  # First row
print('second column:', x[:, 1])  # Second column
print('slicing a sub-tensor:', x[1:3, 0:2])  # Slicing a sub-tensor


tensor([[0.0960, 0.2850, 0.7176],
        [0.5223, 0.7585, 0.0523],
        [0.3432, 0.5486, 0.3696],
        [0.1472, 0.2933, 0.3405],
        [0.0453, 0.4501, 0.3001]])
first row: tensor([0.0960, 0.2850, 0.7176])
second column: tensor([0.2850, 0.7585, 0.5486, 0.2933, 0.4501])
slicing a sub-tensor: tensor([[0.5223, 0.7585],
        [0.3432, 0.5486]])


In [42]:
#extracting values with item
x = torch.rand(5, 3)
print(x)
print('max value:', x.max().item())  # Maximum value
print('min value:', x.min().item())  # Minimum value
print('mean value:', x.mean().item())  # Mean value
print('sum value:', x.sum().item())  # Sum of all elements
#argmax, argmin
print('argmax:', x.argmax().item())  # Index of maximum value
print('argmin:', x.argmin().item())  # Index of minimum value
#nb item only works for 0D tensors ie scalar tensors

tensor([[0.6385, 0.6482, 0.2863],
        [0.0037, 0.1160, 0.1877],
        [0.0181, 0.4074, 0.7145],
        [0.5746, 0.1157, 0.6554],
        [0.0583, 0.4863, 0.5466]])
max value: 0.7144843935966492
min value: 0.0036944150924682617
mean value: 0.36380448937416077
sum value: 5.457067489624023
argmax: 8
argmin: 3


In [52]:
#reshaping
x = torch.rand(4, 4)
print(x)
print('original shape:', x.shape)
print('alternative shape:', x.size())
print('-'*10)
y = x.view(2, 8)  # Reshape to 2x8
print(y)
print('-'*10)
z = x.view(-1, 8)  # Reshape to 2x8 (automatic dimension calculation)
print(z)
print('-'*10)
#flatten
a = x.flatten()  # Flatten the tensor
print(a,'with shape:', a.shape)

tensor([[0.1242, 0.5110, 0.1652, 0.2965],
        [0.8697, 0.5020, 0.1726, 0.3385],
        [0.2633, 0.1402, 0.7215, 0.3171],
        [0.6423, 0.3071, 0.2401, 0.3371]])
original shape: torch.Size([4, 4])
alternative shape: torch.Size([4, 4])
----------
tensor([[0.1242, 0.5110, 0.1652, 0.2965, 0.8697, 0.5020, 0.1726, 0.3385],
        [0.2633, 0.1402, 0.7215, 0.3171, 0.6423, 0.3071, 0.2401, 0.3371]])
----------
tensor([[0.1242, 0.5110, 0.1652, 0.2965, 0.8697, 0.5020, 0.1726, 0.3385],
        [0.2633, 0.1402, 0.7215, 0.3171, 0.6423, 0.3071, 0.2401, 0.3371]])
----------
tensor([0.1242, 0.5110, 0.1652, 0.2965, 0.8697, 0.5020, 0.1726, 0.3385, 0.2633,
        0.1402, 0.7215, 0.3171, 0.6423, 0.3071, 0.2401, 0.3371]) with shape: torch.Size([16])


In [ ]:
#to numpy
x = torch.rand(3, 3)
print(f'tensor x: {x}', type(x))
numpy_array = x.numpy()  # Convert to numpy array
print(f'numpy_array: {numpy_array}', type(numpy_array))
# NB it uses the same memory as the tensor, so modifying one will modify the other
x.add_(1)  # Add 1 to the tensor
print(f'tensor x: {x}', type(x))
print(f'numpy_array: {numpy_array}', type(numpy_array))

y = np.array([[1, 2], [3, 4]])  # Create a numpy array
print(f'numpy_array y: {y}', type(y))
tensor_y = torch.from_numpy(y, dtype=torch.float64)  # Convert to tensor
print(f'tensor_y: {tensor_y}', type(tensor_y))

tensor x: tensor([[0.7122, 0.4159, 0.3849],
        [0.4031, 0.9929, 0.5394],
        [0.5996, 0.1222, 0.7743]]) <class 'torch.Tensor'>
numpy_array: [[0.7122124  0.4159354  0.38485473]
 [0.40308082 0.9929341  0.53942573]
 [0.599593   0.12224352 0.7742742 ]] <class 'numpy.ndarray'>
tensor x: tensor([[1.7122, 1.4159, 1.3849],
        [1.4031, 1.9929, 1.5394],
        [1.5996, 1.1222, 1.7743]]) <class 'torch.Tensor'>
numpy_array: [[1.7122123 1.4159354 1.3848548]
 [1.4030808 1.9929341 1.5394257]
 [1.5995929 1.1222435 1.7742741]] <class 'numpy.ndarray'>
numpy_array y: [[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor_y: tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [62]:
#requires grad
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)  # Create a tensor with gradient tracking
print(x)
y = x + 2  # Perform an operation
print(y)
y.backward(torch.ones_like(y))  # Backpropagation
print(x.grad)  # Gradient of x
# NB requires_grad=True is only needed for the input tensor, not the output tensor
# NB backward() only works for scalar tensors, so we need to pass a gradient of the same shape as y
# NB backward() accumulates gradients, so we need to zero the gradients before each backward pass

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[1., 1.],
        [1., 1.]])
